### ISSUE TITLE
Update RFID Last seen on tool and vend usage, not just GK access

### ISSUE THREAD

**Issue by dpslwk** [NottingHack/database#1]
The rfid tag table has a last seen column which is updated via gatekeeper usage and the sp_check_rfid procedure

```
-- Update the last used time set against the card
update rfid_tags 
set last_used = sysdate()
where rfid_tags.rfid_serial = rfid_serial;
```

For new HMS RIFD access page we would like this number to also be updated when a card is used by a tool or vending machine,
Quick look shows that it needs changing in at least 3 other files

sp_tool_sign_off.sql
sp_tool_sign_on.sql
sp_vend_check_rfid.sql

Alex suggested that this might need a refactor so its only need changes like this in one place in the future

**Comment by geeksareforlife** [comment]
Would it be useful to include a field that shows _what_ saw the card?

**Comment by dpslwk** [comment]
not a bad idea, have a look up table of id's to friendly device names, so its expandable, and then we can show which tool/door/vending machine/note acceptor etc
